name: Terraform AWS Destroy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init with S3 Backend
        run: terraform init -backend-config="bucket=${{ secrets.TF_S3_BUCKET }}" -backend-config="key=${{ secrets.TF_S3_KEY }}" -backend-config="region=${{ secrets.TF_S3_REGION }}"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
